### ISSUE TITLE
Out of memory errors after 2 hours

### ISSUE THREAD

**Issue by laura-dietz** [tuckerowens/trec-car#3]
I get a ton of those: { query=Steubenville, Ohio Climate,
queryid=Steubenville,%20Ohio/Climate}

Then after 2 hours I get this:

Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.lang.String.substring(String.java:1969)
        at java.lang.String.split(String.java:2353)
        at java.lang.String.split(String.java:2422)
        at edu.unh.cs.trec.SystemResults.rankingFromString(SystemResults.java:112)
        at edu.unh.cs.trec.SystemResults.<init>(SystemResults.java:21)
        at edu.unh.cs.trec.Eval.main(Eval.java:20)

real    124m23.260s
user    1856m54.980s
sys     78m49.144s

**Comment by laura-dietz** [comment]
sorry I ran it against a much large query collection.
